language: scala

sudo: required

dist: trusty

jdk:
  - openjdk8
#  - openjdk11

scala:
  - 2.12.11

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.cache/coursier

env:
  global:
    - TRAVIS_NODE_VERSION="5"

addons:
  apt:
    packages:
      - graphviz

before_install:
  - export PATH=${PATH}:./vendor/bundle
  - git fetch --tags

# install:
#   - scripts/travis-setup.sh

# script:
#   - scripts/travis-build.sh

stages:
  - name: test
  # - name: docs
  - name: release
    if: (branch = master AND type = push) OR (tag IS present) AND NOT fork

jobs:
  include:
    # - stage: docs
    #   script: sbt clean makeMicrosite
    - name: build
      script: sbt test
    - name: formatting
      script: sbt checkfmt
    - stage: release
      script: sbt ci-release

branches:
  only:
    - master
    - /v.+/
